name: Compile SRS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'source/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          persist-credentials: false
          fetch-depth: 0

      - name: Download and Set Up sing-box
        run: |
          mkdir -p tmp/compile
          wget -O sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.10.0-alpha.22/sing-box-1.10.0-alpha.22-linux-amd64.tar.gz
          tar zxvf sing-box.tar.gz && rm sing-box.tar.gz
          mv sing-box-1.10.0-alpha.22-linux-amd64/sing-box tmp/compile/
          rm -r sing-box-1.10.0-alpha.22-linux-amd64

      - name: Compile with sing-box
        run: |
          cp source/* tmp/compile/
          cd tmp/compile
          for file in *.json; do
            ./sing-box rule-set compile "$file" -o "${file%.json}.srs"
          done
          cd ../.. && mv binary/adguard .
          rm -r binary/* && mv adguard binary/
          cp tmp/compile/*.srs binary/
          rm -r tmp && ls -l binary

      - name: Check and Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git diff --cached --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
            git commit -m "actions: Update binary format srs" -a
          fi

      - name: Push
        if: env.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
