name: Pull and Convert YAML Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 0"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'zacred0rryn/srs-custom'
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: 'zacred0rryn/srs-custom'
          ref: 'scripts'
          path: '_scripts'

      - uses: actions/checkout@v4
        with:
          repository: 'VirgilClyne/GetSomeFries'
          path: '_httpdns'

      - uses: actions/checkout@v4
        with:
          repository: 'SunsetMkt/anti-ip-attribution'
          path: '_ip-attr'

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          pip install pyyaml

      - name: Set Up
        run: |
          mkdir -p source tmp
          cp _scripts/convert-yaml.py tmp/

      - name: Prepare `HTTP DNS`
        run: |
          cp _httpdns/ruleset/HTTPDNS.Block.yaml tmp/httpdns-block.yaml

      - name: Prepare `IP Attribution`
        run: |
          cd _ip-attr/generated
          for file in rule-provider-*; do
            newname="${file/rule-provider-/ip_attribution-}"
            mv "$file" "$newname"
          done
          cd ../..
          cp _ip-attr/generated/ip_attribution-* tmp/

      - name: Convert
        run: |
          cd tmp && python ./convert-yaml.py && cd ..
          cp tmp/*.json source/

      - name: Clean Up
        run: |
          rm -rf tmp _*
          ls -l source

      - name: Check and Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git diff --cached --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
            git commit -m "actions: Update source format srs" -a
          fi

      - name: Push
        if: env.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Trigger Compilation
        if: env.changes == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/zacred0rryn/srs-custom/actions/workflows/compile.yml/dispatches \
            -d '{"ref":"main"}'
